export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white pt-32 pb-20">
      <div className="max-w-4xl mx-auto px-6">
        <div className="mb-12 border-l-4 border-yellow-400 pl-6">
          <h1 className="text-4xl font-bold tracking-tighter uppercase mb-2">Terms & Conditions</h1>
          <p className="text-neutral-500 font-mono text-sm">LAST UPDATED: JANUARY 2026</p>
        </div>

        <div className="prose prose-neutral max-w-none space-y-8 text-neutral-800">
          <section className="bg-neutral-50 p-6 border border-neutral-200 rounded-lg">
            <p className="text-sm leading-relaxed">
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p className="text-sm mt-4">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <span className="font-bold">boxpox.in</span> (&apos;Website&apos;).
            </p>
          </section>

          <div className="grid gap-8">
            <div className="space-y-4">
              <h2 className="text-xl font-bold flex items-center gap-3">
                <span className="bg-black text-white w-8 h-8 flex items-center justify-center text-xs font-mono">01</span>
                PLATFORM OWNERSHIP
              </h2>
              <p>
                The Platform is owned by with its registered office at <span className="font-bold">1617 sector 70 mohali</span>, a company incorporated under the Companies Act, 1956 <span className="font-bold">7888601710</span> (hereinafter referred to as &apos;Platform Owner&apos;, &apos;we&apos;, &apos;us&apos;, &apos;our&apos;).
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="text-xl font-bold flex items-center gap-3">
                <span className="bg-black text-white w-8 h-8 flex items-center justify-center text-xs font-mono">02</span>
                USER AGREEMENT
              </h2>
              <p>
                Your use of the Platform and services and tools are governed by the following terms and conditions (&quot;Terms of Use&quot;). By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="text-xl font-bold flex items-center gap-3">
                <span className="bg-black text-white w-8 h-8 flex items-center justify-center text-xs font-mono">03</span>
                SERVICE USAGE TERMS
              </h2>
              <ul className="list-none space-y-3 pl-0">
                {[
                  "You agree to provide true, accurate and complete information during registration.",
                  "Neither we nor any third parties provide any warranty as to the accuracy or timeliness of information.",
                  "Your use of our Services is solely at your own risk and discretion.",
                  "The contents of the Platform are proprietary to us; you claim no intellectual property rights.",
                  "You agree to pay us the charges associated with availing the Services.",
                  "You agree not to use the Platform for any purpose that is unlawful or forbidden by Indian laws."
                ].map((item, i) => (
                  <li key={i} className="flex gap-4 items-start border-b border-neutral-100 pb-3">
                    <span className="text-yellow-500 font-mono text-xs pt-1">[{i + 1}]</span>
                    <span className="text-sm">{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="space-y-4">
              <h2 className="text-xl font-bold flex items-center gap-3">
                <span className="bg-black text-white w-8 h-8 flex items-center justify-center text-xs font-mono">04</span>
                JURISDICTION
              </h2>
              <p>
                These Terms and any dispute or claim relating to it shall be governed by and construed in accordance with the laws of India. All disputes shall be subject to the exclusive jurisdiction of the courts in Mohali, Punjab.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
